### ISSUE TITLE
mobile.jpg

### ISSUE THREAD

**Issue by WalterThompson** [dpp/traziotemplates#1]
![mobile](https://cloud.githubusercontent.com/assets/13224321/10707561/e0aeafda-79a8-11e5-9240-3c6092e33040.jpg)

**Comment by tinapc** [comment]
Have we a bug on mobile version?

**Comment by WalterThompson** [comment]
No bug -- I'm new to GitHub, so I'm trying to find an easy way to upload images to the repository.

**Comment by tinapc** [comment]
Ah ok, so if you have any problem then let me know. Thanks
